- name: install execution client
  tasks:
  - git:
      repo: git@github.com:ad0ll/near-isnt-decentralized.git
      dest: /home/{{ ansible_user_id }}/execution-client
      version: main
      key_file: /home/{{ ansible_user_id }}/.ssh/id_rsa #TODO Should be removed before submission
  - name: install dependencies
    shell: /bin/bash -c "source ~/.nvm/nvm.sh && cd /home/{{ ansible_user_id }}/execution-client && yarn install && yarn build"

  # TODO install service
  # https://wiki.debian.org/systemd/Services