- name: Install execution client
  hosts: localhost
  become: true
  vars:
    account_id: "garbage7.testnet"
    node_name: "node1"
    coordinator_id: "dev-1667685039748-17418812844752"
    bounty_storage_dir: "/root/.local/bounty_storage/"
    installation_dir: "/root/near-isnt-decentralized2/execution-client"
  tasks:
    - name: install system
      include: tasks/install-client.yaml
