- include: source_nvm.yaml
- name: Fetch repo
  ansible.builtin.git:
    repo: git@github.com:ad0ll/near-isnt-decentralized.git
    dest: "{{ home }}/near-isnt-decentralized2"
    version: main
    key_file: "{{ home }}/.ssh/id_rsa" # TODO Should be removed before submission
    force: true
- name: Create storage directory
  ansible.builtin.file:
    path: "{{ bounty_storage_dir }}"
    state: directory
    recurse: true
- name: Install execution client
  ansible.builtin.shell: 
    cmd: | 
      yarn install
      yarn tsc
    chdir: "{{ home }}/near-isnt-decentralized2/execution-client"
- name: Install default .env
  ansible.builtin.template:
    src: ../files/default.env.j2
    dest: "{{ home }}/near-isnt-decentralized2/execution-client/.env"
    force: true
- name: Copy ecosystem.config.js to directory
  ansible.builtin.template:
    src: ../files/ecosystem.config.js.j2
    dest: "{{ installation_dir }}/ecosystem.config.js"
#- name: Get pm2 startup script
#  ansible.builtin.shell: 
#    cmd: pm2 startup
#    chdir: "{{ installation_dir }}"
#  register: pm2_startup
#- name: Register startup script
#  ansible.builtin.shell:
#    cmd: "{{ pm2_startup.stdout_lines[-1] }}"
#  become: true
#- name: Start execution client
#  ansible.builtin.shell:
#    cmd: pm2 restart index
#    chdir: "{{ installation_dir }}"
#- name: Start execution client
#  ansible.builtin.shell:
#    cmd: pm2 start
#    chdir: "{{ installation_dir }}"